---
- hosts: mywebservers
  become: yes
  tasks: 
  - name: install java on ubuntu
    apt:
      name: "{{myjavapackforubuntu}}"
      state: present
    when: ansible_os_family=="Debian"

  - name: install java on RedHat
    yum:
      name: "{{myjavapackforredhat}}"
      state: present
    when: ansible_os_family=="RedHat"