---
- hosts: 172.31.17.196
  become: yes
  tasks:
  - name: i want to execute linux command
    command:
      cmd: hostname -f
    register: myresult

    
  - name:  i want to display  myresult
    debug:
      msg: "{{myresult}}"
    