---
- hosts: all
  become: yes
  tasks: 
  - name: install websever on ubuntu ansible nodes
    apt:
      name: apache2
      state: present
    when: ansible_os_family=="Debian"

  - name: install websever on RedHat ansible nodes
    yum:
       name: httpd
       state: present 
    when: ansible_os_family=="RedHat"